version: '3'

services:

  postgres:
    container_name: 'mailer_db'
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./dumps:/mailer/dumps
      - ./data/mailer_db:/var/lib/mailer_db/data

  redis:
    container_name: 'mailer_redis'
    image: redis:alpine
    ports:
      - '6379:6379'

  flower:
    container_name: 'mailer_flower'
    image: mher/flower:0.9.5
    command: ["--app mailer", "--broker=redis://redis:6379/0"]
    ports:
      - '5555:5555'
    restart: unless-stopped