# Generated by Django 3.2 on 2022-05-29 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import notify.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('subject', models.CharField(default='', max_length=128, verbose_name='Заголовок')),
                ('html', models.TextField(max_length=5000, validators=[notify.validators.validate_html], verbose_name='HTML')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=128, verbose_name='Почта')),
                ('user', models.ForeignKey(help_text='Пользователь, создавший получателя.', on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('subject', models.CharField(default='', max_length=128, verbose_name='Заголовок')),
                ('html', models.TextField(max_length=5000, validators=[notify.validators.validate_html], verbose_name='HTML')),
                ('delivery_status', django_fsm.FSMField(choices=[(2, 'Отклонено'), (0, 'Ожидает'), (1, 'Доставлено')], default=0, editable=False, max_length=50, protected=True, verbose_name='Состояние доставки')),
                ('read_status', django_fsm.FSMField(choices=[(0, 'Ожидает'), (1, 'Не прочитано'), (2, 'Прочитано')], default=0, editable=False, max_length=50, protected=True, verbose_name='Состояние прочтения')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта получателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ('id',),
            },
        ),
    ]
