# Generated by Django 3.2 on 2022-05-29 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='postpone_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, создавший получателя.', on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
