# Generated by Django 3.2 on 2022-05-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20220529_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='postpone_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name=''),
        ),
    ]
