# Generated by Django 3.2 on 2022-05-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('notify', '0003_alter_notify_postpone_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOffPeriodicTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic_task', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask', verbose_name='Периодическая задача')),
            ],
            options={
                'verbose_name': 'Одноразовая задача',
                'verbose_name_plural': 'Одноразовые задачи',
                'ordering': ('id',),
            },
        ),
    ]
