# Generated by Django 3.2 on 2022-05-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_oneoffperiodictask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneOffPeriodicTask',
        ),
    ]
