# Generated by Django 3.2 on 2022-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_delete_oneoffperiodictask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='URL Вебхука')),
                ('base_open_tracking_url', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='URL Трекера открытий письма')),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурация',
                'ordering': ('id',),
            },
        ),
    ]
