# Generated by Django 3.2 on 2022-05-30 17:48

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='webhook_url',
        ),
        migrations.AlterField(
            model_name='notify',
            name='delivery_status',
            field=django_fsm.FSMField(choices=[('0', 'Ожидает'), ('1', 'Доставлено'), ('2', 'Отклонено')], default='0', editable=False, max_length=50, protected=True, verbose_name='Состояние доставки'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='read_status',
            field=django_fsm.FSMField(choices=[('1', 'Не прочитано'), ('2', 'Прочитано')], default='1', editable=False, max_length=50, protected=True, verbose_name='Состояние прочтения'),
        ),
    ]
