# Generated by Django 3.2 on 2022-05-30 17:49

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_auto_20220530_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='read_status',
            field=django_fsm.FSMField(choices=[('0', 'Не прочитано'), ('1', 'Прочитано')], default='0', editable=False, max_length=50, protected=True, verbose_name='Состояние прочтения'),
        ),
    ]
